name: Add IAM issues to Internal projects

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to IAM Internals
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/kayathiri4/projects/1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: Type/Internal
          label-operator: OR 
